# Generated by Django 5.2.10 on 2026-02-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
